apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appdeployment.name }}
  labels:
    app: {{ .Values.appdeployment.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appdeployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appdeployment.name }}
    spec:
      containers:
      - name: {{ .Values.appdeployment.name }}
        image: {{ .Values.appdeployment.image }}
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: {{ .Values.name }}

