apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: default
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appdeployment.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
