version: "3.7"
services:
  portfolioserver:
    container_name: portfolioserver
    image: portfolioserverimg
    links:
      - portfoliodb
    depends_on:
      - "portfoliodb"
    ports:
      - "8000:5000"
    environment:
      - MONGODB_URI=mongodb://root:password@portfoliodb:27017
    networks:
      - "mynet"
      # - "frontend"
      
  
  portfoliodb:
    container_name: portfoliodb
    image: mongo:6.0.2
    ports:
      - "27017:27017"
    networks:
      - "mynet"
    volumes:
        - ./database/backup:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # nginx:
  #   container_name: nginx
  #   image: nginx:1.21.6
  #   ports:
  #     - 81:80
  #   volumes:
  #     - ./conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./server/templates:/usr/share/nginx/html
  #   depends_on:
  #     - portfolioserver
  #   networks:
  #     - "frontend"


networks:
  mynet:
    name: mynet
    driver: bridge
  # frontend:
  #   name: frontend
  #   driver: bridge
